#!/bin/bash
ROOT_PATH=$(realpath .)
UDMIDIR="$HOME/udmi"
SRC_LIST=pubber_list.txt
PUBBER_OUT=/tmp/pubber.out
PROJECT_ID=daq1-273309

cd $UDMIDIR
ls


while read -u 7 device_id pubber_opts; do
    rm -f $PUBBER_OUT && touch $PUBBER_OUT
    echo $device_id
    serial_no=pubber-$RANDOM
    bin/pubber $ROOT_PATH $PROJECT_ID $device_id $serial_no $pubber_opts 2>&1 | tee $PUBBER_OUT &
    tail -f $PUBBER_OUT | grep -m 1 "sending test message #0"
    kill $(ps ax | fgrep pubber | fgrep java | awk '{print $1}')

done 7< $ROOT_PATH/$SRC_LIST
